### ISSUE TITLE
Change in folders on Mac

### ISSUE THREAD

**Issue by tomjwinter** [wpilibsuite/2024Beta#3]
I just installed the software on a MacBook Pro (OSX Sonoma 14.0)
In past years, wpilib installed into the `/Users/_Username_/wpilib/_YEAR_` folder.
This year, the beta version installed into the `/Users/_Username_/Documents/wpilib/2024` folder. Not sure if that was intentional or not.
However, the log files went into `/Users/_Username_/wplib/2024/logs` folder.  Again, not sure if that was intentional or not.
I did not see it listed in the 2024 changes.

**Comment by sciencewhiz** [comment]
There wasn't anything intentional that changed the directory. It could be that the upgrade to .net 8 changed the value of `Environment.SpecialFolder.Personal`, or it could be that macOS 14 changed it. https://github.com/wpilibsuite/WPILibInstaller-Avalonia/blame/588ea0885b755292903d68bd6942d277d170113d/WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs#L376

I'm assuming that you had macOS 13 installed when you installed the 2023 version. One test that would be helpful would be to install the 2023.4.3 release on macOS 14 and see where that is put. If it's in `/Users/_Username_/Documents/wpilib/2024` that would indicate the change is in behavior is macOS 14 and if it's in `/Users/_Username_/wpilib/_YEAR_` that would indicate that change is in .Net 8.

**Comment by sciencewhiz** [comment]
Looks like that was a change in .Net 8. https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix

**Comment by tomjwinter** [comment]
Yes, it looks like that is the issue.  I tried to test out the fix, but can't get the installer to build on my mac, so I will wait for the next version build to try it out.

**Comment by sciencewhiz** [comment]
You can try the CI build here: https://github.com/wpilibsuite/WPILibInstaller-Avalonia/actions/runs/6520547874?pr=352
